Create validate.yml
mentoriaiac/iac-modulo-cloudflare pull request #3
Opened 2021-04-06 23:40 UTC by klebercabral

Criar CI para Módulo Terraform Cloudflare atender #2 

Participação

@edsoncelio
@mmmarceleza
@marcelomansur
@estolano-thales
@gpxlnx

2021-04-06 23:41 UTC, edsoncelio approved these changes
Para uma primeira versão apenas para validar, acho que está ok.

2021-04-07 00:55 UTC, estolano-thales commented
Acompanhei a call, tbm ok pra mim.

2021-04-10 18:05 UTC, gomex requested changes

2021-04-10 18:05 UTC, gomex commented on .github/workflows/validate.yml
> +    runs-on: ubuntu-latest
Deveria ter a versão específica do ubuntu e não a latest.

2021-04-10 18:05 UTC, gomex commented on .github/workflows/validate.yml
> +  workflow_dispatch:
Por que estamos usando esse evento manual aqui?

2021-04-11 03:30 UTC, klebercabral commented on .github/workflows/validate.yml
> +    runs-on: ubuntu-latest
Vou ajustar para ubuntu-18.04 conforme recomendação:
https://github.com/DadosAbertosDeFeira/iac/blob/main/README.md#requisitos-1

2021-04-11 03:34 UTC, klebercabral commented on .github/workflows/validate.yml
> +  workflow_dispatch:
Vou ajustar para seguir este padrão:
https://github.com/DadosAbertosDeFeira/iac/blob/f9608692ee4fcd7e179e57c2c5bc158d0081751c/.github/workflows/ci.yml#L3

2021-04-12 21:05 UTC, gomex approved these changes

2021-04-12 21:06 UTC, merged